name: mono_app
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - quiz_app
  - packages/core
  - packages/design_system
  - packages/shared
  - packages/modules/auth
  - packages/modules/home
  - packages/modules/question_bank
  - packages/modules/quiz
  - packages/modules/user_profile
  - packages/features/auth_flow
  - packages/features/home_flow
  - packages/features/onboarding
  - packages/features/profile_flow
  - packages/features/quiz_flow
  - packages/features/stats_flow

dev_dependencies:
  melos: ^6.3.0
  flutter_lints: ^5.0.0
